apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{cookiecutter.name | jsonify}}
  description: {{cookiecutter.description | jsonify}}
  annotations:
    backstage.io/techdocs-ref: url:{{cookiecutter.storePath}}
spec:
  type: documentation
  lifecycle: experimental
  owner: {{cookiecutter.owner | jsonify}}
